# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfJM1yp7JIi7XjDeTR6S1Y8O1kEXfgT5
"""

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 22, 19, 21, 20],
    "Grade": ["A", "B", "A", "C", "B"],
    "Marks": [85, 78, 92, 65, 74]
}

students_data = pd.DataFrame(data)

print("Full DataFrame:")
print(students_data)

print("\nFirst 3 rows:")
print(students_data.head(3))

print("\nName and Marks columns:")
print(students_data[["Name", "Marks"]])

print("\nStudents with Grade A:")
print(students_data[students_data["Grade"] == "A"])