# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfJM1yp7JIi7XjDeTR6S1Y8O1kEXfgT5
"""

import numpy as np

A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 4, 3, 2, 1])


print(A + B)
print(A - B)
print(A * B)
print(A / B)

dot_product = np.dot(A, B)

reshaped_A = A.reshape(5,1)

print("Mean of A =", A.mean())
print("Max of A =", A.max())
print("Min of A =", A.min())

print("Dot Product =", dot_product)

print("Reshaped A:")
print(reshaped_A)