# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLsUpaL7uyxK85gZ8J3-vbM7Ak3FtDHX
"""

import matplotlib.pyplot as plt

days_of_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
temperatures = [20, 22, 23, 21, 24, 26, 25]

plt.figure(figsize=(10, 6))
plt.plot(days_of_week, temperatures, marker='o', linestyle='-', color='skyblue')

plt.xlabel('Day of the Week')
plt.ylabel('Temperature (°C)')
plt.title('Temperature Variation Over a Week')

plt.grid(True, linestyle='--', alpha=0.7)


plt.show()